server:
  port: 8761
spring:
  cloud:
    config:
      uri:
      - http://localhost:8888
      username: configadmin
      password: welcome1
eureka:
  client:
    enabled: false
    fetch-registry: false
